### ISSUE TITLE
Support for vector and matrix scaling methods

### ISSUE THREAD

**Issue by dsvrsec** [fabiankueppers/calibration-framework#12]
Can netcal support vector and matrix scaling methods

**Comment by fabiankueppers** [comment]
Hi, the class "LogisticCalibration" represents vector scaling as it learns a weight and a bias for each class separately. However, matrix scaling is not supported as it requires much more weights but offers no sufficient calibration performance compared to logistic calibration or temperature scaling in my opinion.
