### ISSUE TITLE
Error in the code of temperature scaling

### ISSUE THREAD

**Issue by dsvrsec** [fabiankueppers/calibration-framework#13]
Based on the formula for TS ,which is softmax(z/T) where T is the Temperature.But in the repository,the code represents softmax(z*T),where weight T is calculated.Can you please confirm this.

**Comment by fabiankueppers** [comment]
Hi, yes you're right, we're using a multiplication instead of a division as the former one is numerically more stable during optimization. So the model learns a weight w = 1/T instead of the temperature directly.
