### ISSUE TITLE
Reliability diagram correctness

### ISSUE THREAD

**Issue by dsvrsec** [fabiankueppers/calibration-framework#14]
Hi,when I tried to plot the Reliability diagram for CIFAR 10 resnet110 model,the plot contains the blue region's filled for low level bins also even though there are no probability values present in those bins.Is this anything that is default in the code

**Comment by fabiankueppers** [comment]
Hi, yes you're right, the default behavior is to draw the blue bar to the perfect calibration diagonal. Actual, you cannot change this behavior.
