### ISSUE TITLE
Where can I view the paper "Bayesian Confidence Calibration for Epistemic Uncertainty Modelling"?

### ISSUE THREAD

**Issue by krenerd** [fabiankueppers/calibration-framework#18]
Where can I view the paper "Bayesian Confidence Calibration for Epistemic Uncertainty Modelling"?
I can't find it anywhere on the internet including on google scholar search.  I can only find is the abstract. I would like to have a read for reference to my paper related to model calibration. 
If the paper is yet published, can you please generously send me a copy to sieunpark77@gmail.com?
Thank you.

**Comment by fabiankueppers** [comment]
Now available as preprint: https://arxiv.org/abs/2109.10092
