### ISSUE TITLE
Mean Accuracy Treshold

### ISSUE THREAD

**Issue by mathieulallier807** [fabiankueppers/calibration-framework#23]
How is the mean accuracy in the ReliabilityDiagram Calculated? What is the threshold used to select a binary outcome?
Would it be possible to add a parameter to use as a threshold?

Thanks

**Comment by fabiankueppers** [comment]
Hi @mathieulallier807, sorry for the late response. The calibration target for binary classification calibration is rather the relative frequency of the positive class, i.e., of label "1", than the accuracy. 
For example, consider N = 100 images of a dataset with binary ground-truth labels Y ∈ {0, 1}, where 50 images are labeled as Y = 0 and 50 images with Y = 1. Furthermore, consider a classification model with a sigmoidal output in [0, 1], indicating
its confidence for Y = 1. In our example, this model is able to always predict the correct ground-truth
label with confidences P̂= 0 and P̂= 1 for Ŷ = 0 and Ŷ = 1, respectively. Thus, the network is
able to achieve an accuracy of 100% but with an average confidence of 50%. Therefore, we consider
the relative frequency for Y = 1 in a binary classification task as the calibration goal that is also 50%
in this scenario.

I hope this helps.
