### ISSUE TITLE
ece algorithm has bug using for binary classification

### ISSUE THREAD

**Issue by sunxin000** [fabiankueppers/calibration-framework#25]
the parameter I pass: X is the proba, y is the label vector. 
I found that the result is different from which i get from tfp.stats.expected_calibration_error.
I check both codes, and I found that it is different to caculate the acc for each bin. I think the code in netcal.metrics.MIscalibration.py 386 line may be wrong, the code is
* matched = np.array(y)
but even if y true label is zero, it can be matched as long as the predicted label is 0.

In your code, you calculate the acc as the portion of the positive sample of the total samples when the y is one dim.

**Comment by fabiankueppers** [comment]
Hi, thanks for your comment. Are you in an object detection setting? If so, the method does not perform a matching of bounding boxes with the ground-truth but rather expects the already "matched" label flags. In this case, you have to do the bounding box matching by yourself and provide the results to the method. Hope this helps.

**Comment by fabiankueppers** [comment]
I close this issue for now. If you feel that it is still some kind of error, please re-open.
