### ISSUE TITLE
Missing sdist URL in pypi

### ISSUE THREAD

**Issue by MischaPanch** [fabiankueppers/calibration-framework#5]
Hi,

thank you for the library! I am using it to compute some calibration metrics like ECE and so on, so it came in really handy.

I have one small request: could you provide a link to the sdist in pypi? The reason I need it is a fairly unusual one - I want to use netcal withi a custom pyodide bin in a frontend application and wanted to create a pyodide package with their mkpgk wrapper (see https://pyodide.readthedocs.io/en/latest/new_packages.html). This failed with the error
Exception: No sdist URL found for package netcal (https://pypi.org/project/netcal/).

I can root around it, of course, but it would be an easy fix to make it work :)

**Comment by fabiankueppers** [comment]
Hi, thanks for your comment. Glad to hear that somebody is using this stuff :)
I uploaded the sdist to pypi, please check if you're able to access it.

**Comment by MischaPanch** [comment]
Thank you, I can access it from pypi now
