### ISSUE TITLE
Use of nan parameters in np.nan_to_num requires numpy>=1.17

### ISSUE THREAD

**Issue by F-A** [fabiankueppers/calibration-framework#6]
In [Miscalibration.py, L233](https://github.com/fabiankueppers/calibration-framework/blob/80194433da20e1784f9f516f800652bc9f325fbb/netcal/metrics/Miscalibration.py#L233) you are using the "nan" parameters in np.nan_to_num. This parameters [was added in version 1.17](https://numpy.org/doc/stable/release/1.17.0-notes.html#new-keywords-added-to-nan-to-num) of numpy. You probably need to update the requirements for your package to use numpy 1.17 :)

**Comment by fabiankueppers** [comment]
Thanks for your recommendation! This will be fixed with the next update.

**Comment by fabiankueppers** [comment]
Close Issue by new release [1.1.3](https://github.com/fabiankueppers/calibration-framework/releases/tag/r1.1.3).
