### ISSUE TITLE
Can this be used in face verifaction and how?

### ISSUE THREAD

**Issue by zh794390558** [fabiankueppers/calibration-framework#7]

**Comment by fabiankueppers** [comment]
Hi, could you please give me more details what you're trying to do? I am not familiar with face verification. But as long as you have a ground-truth and you obtain some probability-like scores, I think you can surely use calibration.

**Comment by zh794390558** [comment]
You can think face verification as binary classfication, I want to calibrate this score and do multi model fusion.

**Comment by fabiankueppers** [comment]
Sure, if it's a kind of binary classification you can simply pass the confidence scores as a Numpy array of shape (N,) to the calibration model with according ground truth of shape (N,).
Seems to be very interesting, please keep me informed if it's applicable to your task.

**Comment by zh794390558** [comment]
I have test, scaling is not improve EER, but some binning can work. 
Since given label to do calibration, how can I know this calibration is overfit or not? Which data should I do calibration? 
For speaker verification,  using cosine to score two embed, which is test on open data.

**Comment by fabiankueppers** [comment]
Did you find a solution? I'm closing this issue for now.
