### ISSUE TITLE
Pickling objects

### ISSUE THREAD

**Issue by dafrenchyman** [fabiankueppers/calibration-framework#9]
I wanted to pickle the `LogisticCalibration()` class after I had fit it (for later re-use), but I was getting an error related to `can't pickle _thread.Rlock objects`.

I was able to find a work-around by setting `logger` in the class no `None`. Seems a bit hacky, but it did work. Might be something to think about in future releases

**Comment by fabiankueppers** [comment]
Thanks for your comment. I already faced similar problems in conjunction with the logger class. I will definitely take this into account in future releases

**Comment by fabiankueppers** [comment]
Close Issue by new release [1.1.3](https://github.com/fabiankueppers/calibration-framework/releases/tag/r1.1.3).

**Comment by VCBE123** [comment]
Is there any tutorial about how to store the fitted LogisticCalibration?  I need to reuse it. By the way, thanks for your fantastic Project!

**Comment by fabiankueppers** [comment]
Hi @VCBE123 thanks for pointing out. Indeed, this is a point I've missed to document in the README. You can simply store and reload a model by
```
lr = LogisticCalibration()

# store on disk
lr.save_model("foo/bar/model.pkl")

# load from disk
lr.load_model("foo/bar/model.pkl")
```

Hope this helps!

**Comment by VCBE123** [comment]
Hi @fabiankueppers 
thank you for your clean demo. I have another question.
Since I can save the trained model to a **.pkl** file, is there any advice for reconstructing the model in C/C++ for development usage?

**Comment by VCBE123** [comment]
> Hi @fabiankueppers thank you for your clean demo. I have another question. Since I can save the trained model to a **.pkl** file, is there any advice for reconstructing the model in C/C++ for development usage?

Finally, I  dive into the code and reconstruct the model. 

```python
from netcal.scaling import LogisticCalibration
import torch
import torch.nn.functional as F
import numpy as np

lr = LogisticCalibration(detection=True, use_cuda=False)
lr.load_model("lr_5.pkl")

inputs = np.random.randn(10, 5)
out = lr.transform(inputs)

model_weight = torch.load("lr_5.pkl")["_sites"]

inputs = torch.from_numpy(inputs)
weight = torch.from_numpy(model_weight["weights"]['values']).reshape(-1, 1)
bias = torch.from_numpy(model_weight["bias"]['values']).reshape(-1, 1)


def inferse_sigmoid(confidence):
    epsilon = float(torch.finfo(confidence.dtype).eps)
    clipped = torch.clamp(confidence, epsilon, 1. - epsilon)
    inv_clipped = torch.clamp(1. - confidence, epsilon, 1. - epsilon)

    logit = torch.log(clipped) - torch.log(inv_clipped)
    return logit


inputs[:, 0] = inferse_sigmoid(inputs[:, 0])
out_r = torch.sigmoid(torch.mm(inputs, weight) + bias).squeeze_(1).numpy()

assert np.allclose(out, out_r)
```
